# Generated by Django 2.1.5 on 2019-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cpu_frequency', models.DecimalField(decimal_places=5, max_digits=10)),
                ('voltage', models.DecimalField(decimal_places=5, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=5, max_digits=10)),
                ('num_threads', models.IntegerField()),
                ('memory_consumption', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
