# Generated by Django 2.1.5 on 2019-01-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center_monitor', '0001_create_application_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='report_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
